/**
 * AnnaSetu — Donor Mock Data
 *
 * Phase 19 canonical scenario:
 * Donor: Green Leaf Catering · 40 kg vegetarian cooked meals
 * Receivers: Seva Community Kitchen (12 kg), Anna Sadan Trust (8 kg), Sahara Community Home (20 kg)
 * Driver: Arjun Sharma · Insulated Van
 */
import type { DonorData } from '@/lib/types/donor'

export const DONOR_DATA: DonorData = {
  businessName: 'Green Leaf Catering',
  verified: true,
  donation: {
    id: 'AS-GL-0001',
    name: 'Vegetarian Cooked Meals',
    type: 'Vegetarian',
    category: 'Cooked Meals',
    quantity: 40,
    unit: 'kg',
    status: 'In transit',
    createdAt: 'Today, 2:10 PM',
    deadline: 'Today, 6:00 PM',
    allocation: 40,
    priority: 94,
    image: '/placeholder.jpg',
    description: 'Freshly prepared North Indian thali — roti, dal, sabzi, rice. Refrigerated pickup.',
    storage: 'Insulated containers · 4 °C',
    packaging: 'Sealed food-grade stainless steel containers',
    preparation: 'Prepared today at 2:00 PM',
    pickupAddress: 'Plot 14, Ashok Nagar, C-Scheme, Jaipur, Rajasthan',
    driver: 'Arjun Sharma',
    vehicle: 'Insulated Van',
    eta: 11,
    distance: 9.1,
    receivers: [
      { name: 'Seva Community Kitchen', quantity: 12, address: 'Sector 3, Malviya Nagar, Jaipur' },
      { name: 'Anna Sadan Charitable Trust', quantity: 8, address: 'Amrapali Marg, Vaishali Nagar, Jaipur' },
      { name: 'Sahara Community Home', quantity: 20, address: 'Madhyam Marg, Mansarovar, Jaipur' },
    ],
  },
  donations: [
    {
      id: 'AS-GL-0001',
      name: 'Vegetarian Cooked Meals',
      type: 'Vegetarian',
      category: 'Cooked Meals',
      quantity: 40,
      unit: 'kg',
      status: 'In transit',
      createdAt: 'Today, 2:10 PM',
      deadline: 'Today, 6:00 PM',
      allocation: 40,
      priority: 94,
      image: '/placeholder.jpg',
      description: 'Freshly prepared North Indian thali — roti, dal, sabzi, rice. Refrigerated pickup.',
      storage: 'Insulated containers · 4 °C',
      packaging: 'Sealed food-grade stainless steel containers',
      preparation: 'Prepared today at 2:00 PM',
      pickupAddress: 'Plot 14, Ashok Nagar, C-Scheme, Jaipur, Rajasthan',
      driver: 'Arjun Sharma',
      vehicle: 'Insulated Van',
      eta: 11,
      distance: 9.1,
      receivers: [
        { name: 'Seva Community Kitchen', quantity: 12, address: 'Sector 3, Malviya Nagar, Jaipur' },
        { name: 'Anna Sadan Charitable Trust', quantity: 8, address: 'Amrapali Marg, Vaishali Nagar, Jaipur' },
        { name: 'Sahara Community Home', quantity: 20, address: 'Madhyam Marg, Mansarovar, Jaipur' },
      ],
    },
    {
      id: 'AS-GL-0000',
      name: 'Bakery Assortment',
      type: 'Vegetarian',
      category: 'Bakery',
      quantity: 18,
      unit: 'kg',
      status: 'Delivered',
      createdAt: 'Yesterday, 5:20 PM',
      deadline: 'Yesterday, 8:00 PM',
      allocation: 18,
      priority: 88,
      image: '/placeholder.jpg',
      description: 'Fresh bakery items packed for same-day rescue.',
      storage: 'Room temperature',
      packaging: 'Paper bakery boxes',
      preparation: 'Prepared yesterday',
      pickupAddress: 'Plot 14, Ashok Nagar, C-Scheme, Jaipur, Rajasthan',
      receivers: [{ name: 'Seva Community Kitchen', quantity: 18, address: 'Sector 3, Malviya Nagar, Jaipur' }],
    },
    {
      id: 'AS-GL-0099',
      name: 'Rice and Dal',
      type: 'Vegetarian',
      category: 'Rice / Dal',
      quantity: 26,
      unit: 'kg',
      status: 'Matched',
      createdAt: '18 Sep, 12:08 PM',
      deadline: '18 Sep, 4:00 PM',
      allocation: 26,
      priority: 91,
      image: '/placeholder.jpg',
      description: 'Cooked rice and dal from lunch service.',
      storage: 'Refrigerated · 4°C',
      packaging: 'Sealed containers',
      preparation: 'Prepared 18 Sep',
      pickupAddress: 'Plot 14, Ashok Nagar, C-Scheme, Jaipur, Rajasthan',
      driver: 'Meena Kapoor',
      vehicle: 'Bike',
      eta: 28,
      distance: 5.4,
      receivers: [{ name: 'Anna Sadan Charitable Trust', quantity: 26, address: 'Amrapali Marg, Vaishali Nagar, Jaipur' }],
    },
    {
      id: 'AS-GL-0098',
      name: 'Seasonal Fruits',
      type: 'Vegetarian',
      category: 'Fruits',
      quantity: 12,
      unit: 'kg',
      status: 'Delivered',
      createdAt: '15 Sep, 10:30 AM',
      deadline: '15 Sep, 3:00 PM',
      allocation: 12,
      priority: 86,
      image: '/placeholder.jpg',
      description: 'Surplus seasonal fruit from retail display.',
      storage: 'Cool storage',
      packaging: 'Reusable crates',
      preparation: 'Sorted 15 Sep',
      pickupAddress: 'Plot 14, Ashok Nagar, C-Scheme, Jaipur, Rajasthan',
      receivers: [{ name: 'Sahara Community Home', quantity: 12, address: 'Madhyam Marg, Mansarovar, Jaipur' }],
    },
  ],
  notifications: [
    { id: 'n1', title: 'Driver is 2.4 km away.', body: 'Arjun Sharma is heading to your pickup location.', time: '5 min ago', urgency: 'urgent' },
    { id: 'n2', title: 'Your 40 kg donation has been matched.', body: 'Allocated to 3 receivers: Seva Community Kitchen, Anna Sadan Trust, and Sahara Community Home.', time: '32 min ago', urgency: 'success' },
    { id: 'n3', title: 'Pickup has been verified.', body: 'GPS, OTP and package seal AS-GL-000047 checks passed.', time: '1 hr ago', urgency: 'success' },
    { id: 'n4', title: 'Your rescue reached a milestone.', body: 'You have now rescued 1,000 kg of food.', time: 'Yesterday', urgency: 'info' },
  ],
  impact: {
    rescued: 1240,
    meals: 3720,
    co2: 2.4,
    rescues: 38,
    monthly: [
      { month: 'Apr', rescued: 70, meals: 210 },
      { month: 'May', rescued: 95, meals: 285 },
      { month: 'Jun', rescued: 110, meals: 330 },
      { month: 'Jul', rescued: 88, meals: 264 },
      { month: 'Aug', rescued: 142, meals: 426 },
      { month: 'Sep', rescued: 180, meals: 540 },
    ],
  },
  reports: [
    { id: 'r1', type: 'Monthly impact report', date: 'September 2024', status: 'Ready' },
    { id: 'r2', type: 'Donation history', date: 'Q3 2024', status: 'Ready' },
    { id: 'r3', type: 'Annual impact report', date: '2024', status: 'Preparing' },
    { id: 'r4', type: 'Transaction report', date: 'September 2024', status: 'Ready' },
  ],
  certificates: [10, 25, 50, 100, 150, 200, 250, 500, 750, 1000, 1500, 2000].map((milestone) => ({
    milestone,
    achieved: milestone <= 1000,
    date: milestone <= 1000 ? 'Sep 2024' : undefined,
  })),
}
